[tool.poetry]
name = "kantharos-bot"
version = "0.3.0"
description = ""
authors = ["Andre Faria <andremarcalfaria@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.7.3"
pandascore = "^0.2.0"
toml = "^0.10.2"
pytz = "^2021.3"
fuzzywuzzy = "^0.18.0"
pytube = "^11.0.2"
youtube_dl = "^2021.12.17"
PyNaCl = "^1.5.0"
jokeapi = "^1.0.4"
black = "^22.3.0"
python-Levenshtein = "^0.12.2"
dynaconf = "^3.1.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
flake8 = "^4.0.1"
black = "^22.3.0"
mypy = "^0.931"
coverage = "^6.2"
isort = "^5.10.1"
tox = "^3.24.5"
ipython = "^8.0.0"

[tool.poetry.scripts]
kantharos-bot = "kantharos_bot.main:main"

[tool.black]
line-length = 100
target-version = ['py38',"py39","py310"]
include = '\.pyi?$'

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
show_missing = true
fail_under = 0

[tool.isort]
profile = "hug"
src_paths = ["isort", "test"]

[tool.tox]
legacy_tox_ini = """
[tox]
skipsdist = true
envlist = py38,py39,py310

[testenv]
whitelist_externals = poetry
commands =
    poetry install -v
    poetry run isort .
    poetry run black .
    poetry run coverage run -m pytest
    poetry run coverage report
"""

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
