pandascore_endpoint="https://api.pandascore.co"
pandascore_token="pandascore-token-here"
discord_token="discord-token-here"
default_datetime_format="%Y-%m-%dT%H:%M:%SZ"
default_timezone="America/Sao_Paulo"
games = [
    { id=26, name="Valorant",        slug="valorant"          },
    { id=25, name="FIFA",            slug="fifa"              },
    { id=24, name="Rainbow 6 Siege", slug="r6-siege"          },
    { id=23, name="Call of Duty",    slug="cod-mw"            },
    { id=22, name="Rocket League",   slug="rl"                },
    { id=20, name="PUBG",            slug="pubg"              },
    { id=14, name="Overwatch",       slug="ow"                },
    { id=4,  name="Dota 2",          slug="dota-2"            },
    { id=3,  name="CS:GO",           slug="cs-go"             },
    { id=1,  name="LoL",             slug="league-of-legends" }
]
