[ytdl_format_options]
format="bestaudio/best"
restrictfilenames=true
noplaylist=true
nocheckcertificate=true
ignoreerrors=false
logtostderr=false
quiet=true
no_warnings=true
default_search="auto"
source_address="0.0.0.0"  # bind to ipv4 since ipv6 addresses cause issues sometimes

[ffmpeg_options]
options= "-vn"